import type { BookChapter } from "./book.types";

const repoBase = "https://github.com/neonwatty/machine-learning-refined/tree/main";
const pdfBase = `${repoBase}/chapter_pdfs`;
const notesBase = `${repoBase}/notes`;
const exercisesBase = `${repoBase}/exercises`;

export const chapters: BookChapter[] = [
  {
    number: "1",
    title: "Introduction to Machine Learning",
    slug: "introduction-to-machine-learning",
    part: "Orientation",
    intent: "learner",
    summary:
      "Book orientation, taxonomy, and the optimization viewpoint that frames the rest of the text.",
    pdfHref: pdfBase,
    topics: ["taxonomy", "optimization viewpoint", "problem setup"],
  },
  {
    number: "2",
    title: "Zero-Order Optimization Techniques",
    slug: "zero-order-optimization-techniques",
    part: "Optimization",
    intent: "learner",
    summary: "Search, coordinate descent, local methods, and global methods.",
    notesHref: `${notesBase}/2_Zero_order_methods`,
    exercisesHref: `${exercisesBase}/chapter_2`,
    pdfHref: pdfBase,
    topics: ["search", "coordinate descent", "global methods"],
  },
  {
    number: "3",
    title: "First-Order Optimization Techniques",
    slug: "first-order-optimization-techniques",
    part: "Optimization",
    intent: "learner",
    summary: "Gradients, descent geometry, step lengths, and mini-batch methods.",
    notesHref: `${notesBase}/3_First_order_methods`,
    exercisesHref: `${exercisesBase}/chapter_3`,
    pdfHref: pdfBase,
    topics: ["gradients", "descent geometry", "mini-batches"],
  },
  {
    number: "4",
    title: "Second-Order Optimization Techniques",
    slug: "second-order-optimization-techniques",
    part: "Optimization",
    intent: "learner",
    summary:
      "Quadratic approximations, Newton's method, curvature, and nonconvex refinements.",
    notesHref: `${notesBase}/4_Second_order_methods`,
    exercisesHref: `${exercisesBase}/chapter_4`,
    pdfHref: pdfBase,
    topics: ["Newton methods", "curvature", "quadratic models"],
  },
  {
    number: "5",
    title: "Linear Regression",
    slug: "linear-regression",
    part: "Linear learning",
    intent: "reference",
    summary:
      "Least squares, absolute deviations, metrics, and probabilistic framing.",
    notesHref: `${notesBase}/5_Linear_regression`,
    exercisesHref: `${exercisesBase}/chapter_5`,
    pdfHref: pdfBase,
    topics: ["least squares", "regression metrics", "probability"],
  },
  {
    number: "6",
    title: "Linear Two-Class Classification",
    slug: "linear-two-class-classification",
    part: "Linear learning",
    intent: "reference",
    summary: "Logistic regression, perceptrons, SVMs, losses, and metrics.",
    notesHref: `${notesBase}/6_Linear_twoclass_classification`,
    exercisesHref: `${exercisesBase}/chapter_6`,
    pdfHref: pdfBase,
    topics: ["logistic regression", "perceptrons", "SVMs"],
  },
  {
    number: "7",
    title: "Linear Multi-Class Classification",
    slug: "linear-multiclass-classification",
    part: "Linear learning",
    intent: "reference",
    summary:
      "One-versus-all classification, multiclass perceptrons, softmax costs, and metrics.",
    notesHref: `${notesBase}/7_Linear_multiclass_classification`,
    exercisesHref: `${exercisesBase}/chapter_7`,
    pdfHref: pdfBase,
    topics: ["one-versus-all", "softmax", "multiclass metrics"],
  },
  {
    number: "8",
    title: "Linear Unsupervised Learning",
    slug: "linear-unsupervised-learning",
    part: "Linear learning",
    intent: "reference",
    summary:
      "Spanning sets, PCA, recommender systems, K-means, and matrix factorization.",
    notesHref: `${notesBase}/8_Linear_unsupervised_learning`,
    exercisesHref: `${exercisesBase}/chapter_8`,
    pdfHref: pdfBase,
    topics: ["PCA", "K-means", "matrix factorization"],
  },
  {
    number: "9",
    title: "Feature Engineering and Selection",
    slug: "feature-engineering-and-selection",
    part: "Linear learning",
    intent: "reference",
    summary:
      "Histogram features, scaling, missing data, PCA sphering, boosting, and regularization.",
    notesHref: `${notesBase}/9_Feature_engineer_select`,
    exercisesHref: `${exercisesBase}/chapter_9`,
    pdfHref: pdfBase,
    topics: ["feature scaling", "missing data", "regularization"],
  },
  {
    number: "10",
    title: "Principles of Nonlinear Feature Engineering",
    slug: "principles-of-nonlinear-feature-engineering",
    part: "Nonlinear learning",
    intent: "learner",
    summary:
      "Nonlinear regression, classification, multiclass learning, and unsupervised feature maps.",
    notesHref: `${notesBase}/10_Nonlinear_intro`,
    exercisesHref: `${exercisesBase}/chapter_10`,
    pdfHref: pdfBase,
    topics: ["nonlinear features", "classification", "unsupervised learning"],
  },
  {
    number: "11",
    title: "Principles of Feature Learning",
    slug: "principles-of-feature-learning",
    part: "Nonlinear learning",
    intent: "learner",
    summary:
      "Universal approximators, cross-validation, boosting, regularization, and bagging.",
    notesHref: `${notesBase}/11_Feature_learning`,
    exercisesHref: `${exercisesBase}/chapter_11`,
    pdfHref: pdfBase,
    topics: ["universal approximation", "cross-validation", "bagging"],
  },
  {
    number: "12",
    title: "Kernel Methods",
    slug: "kernel-methods",
    part: "Nonlinear learning",
    intent: "reference",
    summary:
      "Fixed-shape universal approximators, the kernel trick, similarity measures, and kernelized optimization.",
    exercisesHref: `${exercisesBase}/chapter_12`,
    pdfHref: pdfBase,
    topics: ["kernels", "similarity", "kernelized models"],
  },
  {
    number: "13",
    title: "Fully Connected Neural Networks",
    slug: "fully-connected-neural-networks",
    part: "Nonlinear learning",
    intent: "learner",
    summary:
      "Multilayer perceptrons, activation functions, optimization, and backprop.",
    notesHref: `${notesBase}/13_Multilayer_perceptrons`,
    exercisesHref: `${exercisesBase}/chapter_13`,
    pdfHref: pdfBase,
    topics: ["MLPs", "activation functions", "backpropagation"],
  },
  {
    number: "14",
    title: "Tree-Based Learners",
    slug: "tree-based-learners",
    part: "Nonlinear learning",
    intent: "reference",
    summary:
      "Regression trees, classification trees, gradient boosting, random forests, and tree cross-validation.",
    exercisesHref: `${exercisesBase}/chapter_14`,
    pdfHref: pdfBase,
    topics: ["trees", "boosting", "random forests"],
  },
];
